version: "3"
services:
  node-app:
    image: thomas340/node-hello-world:0.1.1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
